// Code generated by submsg; DO NOT EDIT.
package messages

import (
	"github.com/edison-moreland/SceneEngine/submsg/runtime/go"
	"io"
)

const (
	EngineMsgCoreReady  submsg.MsgId = 0
	EngineMsgCoreInfo   submsg.MsgId = 1
	EngineMsgPixelBatch submsg.MsgId = 2
)

type EngineServer interface {
	CoreReady(body []byte) error
	CoreInfo(body []byte) error
	PixelBatch(body []byte) error
}

func EngineRouter(s EngineServer) submsg.MsgReceiver {
	return func(id submsg.MsgId, body []byte) error {
		switch id {
		case EngineMsgCoreReady:
			return s.CoreReady(body)
		case EngineMsgCoreInfo:
			return s.CoreInfo(body)
		case EngineMsgPixelBatch:
			return s.PixelBatch(body)
		default:
			return submsg.ErrMsgIdUnknown
		}
	}
}

type EngineClient struct {
	s submsg.MsgSender
}

func NewEngineClient(s submsg.MsgSender) *EngineClient {
	return &EngineClient{s: s}
}
func (c *EngineClient) CoreReady(l uint32, b io.Reader) {
	c.s(EngineMsgCoreReady, l, b)
}
func (c *EngineClient) CoreInfo(l uint32, b io.Reader) {
	c.s(EngineMsgCoreInfo, l, b)
}
func (c *EngineClient) PixelBatch(l uint32, b io.Reader) {
	c.s(EngineMsgPixelBatch, l, b)
}

const (
	CoreMsgInfo        submsg.MsgId = 0
	CoreMsgRenderFrame submsg.MsgId = 1
)

type CoreServer interface {
	Info(body []byte) error
	RenderFrame(body []byte) error
}

func CoreRouter(s CoreServer) submsg.MsgReceiver {
	return func(id submsg.MsgId, body []byte) error {
		switch id {
		case CoreMsgInfo:
			return s.Info(body)
		case CoreMsgRenderFrame:
			return s.RenderFrame(body)
		default:
			return submsg.ErrMsgIdUnknown
		}
	}
}

type CoreClient struct {
	s submsg.MsgSender
}

func NewCoreClient(s submsg.MsgSender) *CoreClient {
	return &CoreClient{s: s}
}
func (c *CoreClient) Info(l uint32, b io.Reader) {
	c.s(CoreMsgInfo, l, b)
}
func (c *CoreClient) RenderFrame(l uint32, b io.Reader) {
	c.s(CoreMsgRenderFrame, l, b)
}
